parameters:
#    back_office_administracion.example.class: BackOffice\AdministracionBundle\Example

services:
#    back_office_administracion.example:
#        class: %back_office_administracion.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
